apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: mqtt
spec:
  type: ClusterIP
  selector:
    app: mqtt-broker
  ports:
    - name: mqtts
      port: 8883
      targetPort: 8883
      protocol: TCP
